<a href="https://colab.research.google.com/github/roghayefazli/Image_classification_conv2D/blob/main/conv2D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPool2D, Flatten, Dense
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.utils import plot_model
from sklearn.utils.class_weight import compute_class_weight
from tensorflow.keras.callbacks import ModelCheckpoint

In [26]:
image_generator = ImageDataGenerator(
    rescale=1./255.,
    shear_range=0.1,
    zoom_range=0.3,
)
image_generator_test = ImageDataGenerator(
    rescale=1./255.
)

In [27]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [28]:
train_data = image_generator.flow_from_directory(
    '/content/drive/MyDrive/test_project/Data',
    target_size=(250, 230),
    color_mode='grayscale',
    class_mode='categorical',
    batch_size=50
)

Found 132 images belonging to 8 classes.


In [29]:
test_data = image_generator_test.flow_from_directory(
    '/content/drive/MyDrive/test_project/Data_test',
    target_size=(250, 230),
    color_mode='grayscale',
    class_mode='categorical',
    batch_size=50
)

Found 42 images belonging to 8 classes.


In [30]:
test_data

In [31]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.callbacks import TensorBoard
from tensorflow.keras.layers import Input,Dense,Flatten,Dropout,Activation,Conv2D,MaxPooling2D

In [32]:
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu',input_shape = (250,230,1)))
model.add(MaxPool2D(pool_size=(2, 2)))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPool2D(pool_size=(2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPool2D(pool_size=(2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPool2D(pool_size=(2, 2)))
model.add(Flatten())
# model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(8, activation='softmax'))

In [33]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [34]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_4 (Conv2D)               │ (None, 248, 228, 32)   │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_4 (MaxPooling2D)  │ (None, 124, 114, 32)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 122, 112, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_5 (MaxPooling2D)  │ (None, 61, 56, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_6 (Conv2D)               │ (None, 59, 54, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_6 (MaxPooling2D)  │ (None, 29, 27, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 27, 25, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_7 (MaxPooling2D)  │ (None, 13, 12, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 9984)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 64)             │       639,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 8)              │           520 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 704,552 (2.69 MB)

 Trainable params: 704,552 (2.69 MB)

 Non-trainable params: 0 (0.00 B)

In [35]:
train_data.classes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
       3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
      dtype=int32)

In [36]:
es = EarlyStopping(monitor='val_loss', mode='min', patience=3)
rlrop = ReduceLROnPlateau(monitor='val_loss', patience=2, factor=0.2, min_lr=0.001)

In [37]:
mch = ModelCheckpoint('hospital.keras', monitor='val_loss', mode='min', save_best_only=True)

In [38]:
history = model.fit(train_data,epochs=30)

Epoch 1/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 11s 2s/step - accuracy: 0.0980 - loss: 0.6490
Epoch 2/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 4s 1s/step - accuracy: 0.1618 - loss: 0.4110
Epoch 3/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 4s 1s/step - accuracy: 0.1606 - loss: 0.3857
Epoch 4/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 4s 1s/step - accuracy: 0.0994 - loss: 0.3805
Epoch 5/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 4s 1s/step - accuracy: 0.1760 - loss: 0.3707
Epoch 6/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 4s 1s/step - accuracy: 0.0982 - loss: 0.3693
Epoch 7/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 4s 1s/step - accuracy: 0.1405 - loss: 0.3658
Epoch 8/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 5s 1s/step - accuracy: 0.1595 - loss: 0.3616
Epoch 9/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 4s 1s/step - accuracy: 0.1535 - loss: 0.3618
Epoch 10/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 4s 2s/step - accuracy: 0.2275 - loss: 0.3598
Epoch 11/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 5s 1s/step - accuracy: 0.2529 - loss: 0.3625
Epoch 12/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 4s 1s/step - accuracy: 0.2989 - loss: 0.3598
Epoch 13/30
3/3 ━━━━━━━━

In [39]:
r=model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step


In [40]:
r

array([[3.48334694e-08, 1.36135372e-06, 1.92512766e-06, 4.37059597e-08,
        2.10115772e-07, 1.41864334e-08, 9.99994636e-01, 1.80000382e-06],
       [6.78499418e-05, 9.88460183e-01, 1.06169134e-02, 1.31451670e-04,
        1.59433012e-06, 4.38747011e-05, 6.46116445e-04, 3.20296349e-05],
       [3.99151235e-04, 1.40980447e-07, 4.45013762e-01, 1.61098503e-02,
        4.74398643e-01, 6.37902096e-02, 2.78918305e-04, 9.39398251e-06],
       [4.40656684e-08, 1.00010951e-08, 4.41380680e-01, 1.56321835e-06,
        2.19274607e-05, 1.30324988e-04, 1.00999443e-06, 5.58464468e-01],
       [3.50391645e-07, 5.59195769e-07, 2.52336118e-04, 4.02454532e-07,
        1.06206271e-05, 9.18397802e-09, 9.99733508e-01, 2.20938136e-06],
       [9.96620772e-11, 8.75615580e-09, 3.75492914e-06, 1.50750132e-08,
        3.53565822e-11, 4.40090986e-08, 4.84476992e-08, 9.99996185e-01],
       [7.85472275e-06, 3.08377821e-08, 2.60080099e-01, 7.35175610e-01,
        2.44547450e-03, 3.52243922e-04, 1.91954360e-03, 1.

In [41]:
model.save('ImageCNN.h5')

In [42]:
from tensorflow.keras.models import load_model

In [43]:
model = load_model('ImageCNN.h5')

In [44]:
import cv2

In [45]:
img_array = cv2.imread('/content/drive/MyDrive/test_project/1.tif',cv2.IMREAD_GRAYSCALE)
new_array = cv2.resize(img_array,(250,230))

In [46]:
t=new_array[:,0]

In [47]:
t

array([246, 247, 246, 250, 251, 252, 251, 254, 250, 255, 255, 255, 255,
       255, 251, 255, 255, 255, 255, 255, 255, 254, 255, 255, 255, 253,
       255, 254, 251, 250, 251, 250, 249, 253, 250, 250, 249, 249, 252,
       249, 244, 247, 249, 251, 250, 248, 251, 247, 246, 255, 247, 248,
       251, 249, 251, 251, 251, 253, 249, 254, 245, 248, 248, 247, 250,
       245, 252, 248, 249, 255, 253, 246, 242, 249, 255, 254, 249, 251,
       252, 249, 253, 252, 253, 251, 253, 253, 254, 253, 255, 255, 253,
       255, 255, 255, 255, 253, 250, 255, 255, 255, 255, 255, 255, 255,
       255, 253, 247, 255, 253, 254, 254, 255, 254, 254, 253, 253, 253,
       253, 251, 254, 252, 254, 253, 253, 253, 254, 251, 255, 254, 254,
       250, 253, 253, 253, 255, 253, 255, 254, 253, 255, 254, 254, 254,
       254, 255, 255, 255, 255, 255, 255, 252, 252, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 252, 255, 253, 255,
       254, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 25

In [ ]:
per = model.predict(new_array)